name: CI
on: pull_request
jobs:
    build-test-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Eslint
              run: yarn lint
            - name: Run Jest tests
              run: yarn test:jest
            - name: Run Cypress tests
              uses: cypress-io/github-action@v2
              with:
                  start: yarn dev
    auto-merge:
        name: Auto-Merge PRs by Dependabot
        needs:
            - build-test-lint
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
          - uses: fastify/github-action-merge-dependabot@v3.0.0
            with:
                target: minor
