name: CI
on:
    pull_request:
        branches: [main]
jobs:
    build-test-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - uses: actions/checkout@v2
            - name: Install modules
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Eslint
              run: pnpm run lint:all
            # - name: Run Jest tests
            #   run: pnpm run test:jest
    auto-merge:
        name: Auto-Merge PRs by Dependabot
        needs:
            - build-test-lint
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: fastify/github-action-merge-dependabot@v3.0.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  target: minor
